[workspace]
members = [
    "old",
    "crates/wgpui-core",
    "crates/wgpui-layout",
    "crates/wgpui-text",
    "crates/wgpui-widgets",
    "crates/wgpui-wgpu",
    "crates/wgpui",
    "crates/wgpui-devtools",
    "crates/wgpui-examples-2",
    "crates/wgpui-compat",
    "crates/wgpui-compat-macros",
    "crates/wgpui-macros",
]
