[workspace]
members = [
    "crates/wgpui-core",
    "crates/wgpui-http-client",
    "crates/wgpui-layout",
    "crates/wgpui-text",
    "crates/wgpui-widgets",
    "crates/wgpui-wgpu",
    "crates/wgpui",
    "crates/wgpui-devtools",
    "crates/wgpui-examples-2",
    "crates/wgpui-compat-macros",
    "crates/wgpui-macros",
]
