//! Native declarative elements and component lifecycle.
//!
//! Elements are short-lived values produced for a frame. Their conversion to
//! [`Description`] is the frontend boundary consumed by reconciliation; the
//! reconciler and scene therefore retain layout and paint data without
//! retaining an element value.

use crate::reconcile::description::{Description, ElementId};
use crate::reconcile::state::{ElementStateStore, StateScope};
use std::sync::Arc;

/// A value that can lower itself into the retained frontend description.
pub trait Element: 'static {
    /// Lower this element into the description consumed by reconciliation.
    fn into_description(self) -> Description;
}

/// Converts a value into a native [`Element`].
pub trait IntoElement: Sized {
    /// The concrete element produced by this conversion.
    type Element: Element;

    /// Convert this value into its concrete element.
    fn into_element(self) -> Self::Element;

    /// Lower this value into the per-frame description.
    fn into_description(self) -> Description {
        Element::into_description(self.into_element())
    }
}

impl<T: Element> IntoElement for T {
    type Element = T;

    fn into_element(self) -> Self::Element {
        self
    }
}

/// A stateful component that keeps an element identity separate from the
/// element's concrete builder value.
pub struct Stateful<E> {
    element: E,
    element_id: Option<ElementId>,
    state_scope: Option<StateScope>,
}

impl<E> Stateful<E> {
    /// Wrap an element in a stateful scope.
    pub fn new(element: E) -> Self {
        Self {
            element,
            element_id: None,
            state_scope: None,
        }
    }

    /// Assign a stable identity to the wrapped element and its state.
    pub fn id(mut self, element_id: impl Into<ElementId>) -> Self {
        let element_id = element_id.into();
        self.state_scope = Some(StateScope::from_path(std::slice::from_ref(&element_id)));
        self.element_id = Some(element_id);
        self
    }

    /// Override the scope used by [`Self::with_state`].
    pub fn state_scope(mut self, state_scope: StateScope) -> Self {
        self.state_scope = Some(state_scope);
        self
    }

    /// The explicit state scope, if one was assigned.
    pub fn scope(&self) -> Option<StateScope> {
        self.state_scope
    }

    /// Access retained state in the scope assigned to this element.
    pub fn with_state<T: 'static, R>(
        &self,
        store: &mut ElementStateStore,
        frame: u64,
        initialise: impl FnOnce() -> T,
        access: impl FnOnce(&mut T) -> R,
    ) -> Option<R> {
        let scope = self.state_scope?;
        store.with_state(
            crate::reconcile::state::StateKey::new::<T>(scope),
            frame,
            initialise,
            access,
        )
    }

    /// Consume the wrapper and return the underlying builder value.
    pub fn into_inner(self) -> E {
        self.element
    }
}

impl<E: IntoElement + 'static> Element for Stateful<E> {
    fn into_description(self) -> Description {
        let Stateful {
            element,
            element_id,
            ..
        } = self;
        let mut description = element.into_description();
        if let Some(element_id) = element_id {
            description = description.id(element_id);
        }
        description
    }
}

/// A stateless component whose value is consumed when it is rendered.
pub trait RenderOnce: 'static + Sized {
    /// Produce this component's native element tree.
    ///
    /// Native `RenderOnce` deliberately receives no window or app context:
    /// element construction is a pure value-to-description step, while
    /// retained services belong to the reconciliation and scene layers.
    fn render(self) -> impl IntoElement + 'static;

    /// Lower this component's rendered tree into the per-frame description.
    fn into_description(self) -> Description {
        IntoElement::into_description(self.render())
    }
}

/// A retained view that is rendered again when its entity is invalidated.
pub trait Render: 'static + Sized {
    /// Produce this view's native element tree for the current frame.
    ///
    /// Native `Render` deliberately receives no window or app context for the
    /// same reason as [`RenderOnce`].
    fn render(&mut self) -> impl IntoElement + 'static;
}

/// Render a view into the description consumed by reconciliation.
pub fn render_description<R: Render>(view: &mut R) -> Description {
    view.render().into_description()
}

/// The element generated by `#[derive(IntoElement)]` for a [`RenderOnce`]
/// component.
pub struct Component<C: RenderOnce> {
    component: C,
}

impl<C: RenderOnce> Component<C> {
    /// Create a component element from its owned component value.
    pub fn new(component: C) -> Self {
        Self { component }
    }

    /// Borrow the component value before it is lowered.
    pub fn component(&self) -> &C {
        &self.component
    }
}

impl<C: RenderOnce> Element for Component<C> {
    fn into_description(self) -> Description {
        self.component.render().into_description()
    }
}

impl Element for Description {
    fn into_description(self) -> Description {
        self
    }
}

impl Element for String {
    fn into_description(self) -> Description {
        Description::raw_text(Arc::from(self))
    }
}

impl Element for &'static str {
    fn into_description(self) -> Description {
        Description::raw_text(Arc::from(self))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::reconcile::description::RawText;
    use crate::reconcile::reconciler::Reconciler;
    use wgpui_layout::taffy_tree::LayoutTree;

    struct Panel {
        children: Vec<Description>,
    }

    impl Element for Panel {
        fn into_description(self) -> Description {
            Description::new::<Self>().children(self.children)
        }
    }

    struct View {
        value: u32,
    }

    impl Render for View {
        fn render(&mut self) -> impl IntoElement + 'static {
            Panel {
                children: vec![Description::new::<u32>().id(self.value as u64)],
            }
        }
    }

    struct Badge(u32);

    impl RenderOnce for Badge {
        fn render(self) -> impl IntoElement + 'static {
            Description::new::<Self>().id(self.0 as u64)
        }
    }

    fn badge(value: u32) -> Description {
        Element::into_description(Component::new(Badge(value)))
    }

    #[test]
    fn render_and_render_once_lower_real_descriptions() {
        let mut view = View { value: 7 };
        let description = render_description(&mut view);
        assert_eq!(description.type_id(), std::any::TypeId::of::<Panel>());
        assert_eq!(description.child_descriptions().len(), 1);
        assert_eq!(badge(9).element_id(), Some(&ElementId::Integer(9)));
    }

    #[test]
    fn component_children_are_reconciled_and_state_survives() {
        let description = Description::new::<Panel>().child(badge(1)).child(badge(2));
        let mut reconciler = Reconciler::new();
        let mut layout = LayoutTree::new();
        let first = reconciler
            .reconcile(description, &mut layout)
            .expect("description should reconcile");
        assert_eq!(first.nodes().len(), 3);

        let state_scope = first.nodes()[1].state;
        let mut state = ElementStateStore::new();
        assert_eq!(
            state.with_state(
                crate::reconcile::state::StateKey::new::<u32>(state_scope),
                1,
                || 0,
                |value| {
                    *value += 1;
                    *value
                },
            ),
            Some(1)
        );
        let second = reconciler
            .reconcile(
                Description::new::<Panel>().child(badge(1)).child(badge(2)),
                &mut layout,
            )
            .expect("description should reconcile");
        assert_eq!(second.nodes()[1].state, state_scope);
        assert_eq!(
            state.with_state(
                crate::reconcile::state::StateKey::new::<u32>(second.nodes()[1].state),
                2,
                || 0,
                |value| *value,
            ),
            Some(1)
        );
    }

    #[test]
    fn stateful_lowers_identity_and_retains_state() {
        let stateful = Stateful::new(Description::new::<u32>()).id("counter");
        let scope = stateful.scope().expect("id assigns a state scope");
        let mut state = ElementStateStore::new();
        assert_eq!(
            stateful.with_state(&mut state, 1, || 3_u32, |value| *value),
            Some(3)
        );
        assert!(state.contains(crate::reconcile::state::StateKey::new::<u32>(scope)));
        let description = Element::into_description(stateful);
        assert_eq!(
            description.element_id(),
            Some(&ElementId::Name("counter".into()))
        );
    }

    #[test]
    fn string_children_lower_to_typed_retained_text_content() {
        let description = IntoElement::into_description("hello native world");
        assert_eq!(description.type_id(), std::any::TypeId::of::<RawText>());
        assert_eq!(description.type_name(), std::any::type_name::<RawText>());
        assert!(description.key().is_some());
        assert!(!description.emits());

        let mut description = description;
        let raw = description.take_raw_text().expect("raw text is preserved");
        assert_eq!(raw.value(), "hello native world");
    }

    #[test]
    fn equal_raw_text_keys_report_no_invalidation() {
        let first = Description::raw_text(Arc::from("same"));
        let second = Description::raw_text(Arc::from("same"));
        assert_eq!(
            first
                .key()
                .expect("raw text has a content key")
                .compare(second.key().expect("raw text has a content key")),
            crate::invalidation::axes::Invalidation::empty()
        );
    }
}
